/*
 * Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0
 */
package net.openhft.chronicle.map.impl;

import net.openhft.chronicle.map.ReplicatedChronicleMap;
import net.openhft.sg.Staged;

/**
 * Staged holder interface that exposes a {@link ReplicatedChronicleMap} from
 * within a compiled context.
 * <p>
 * Implementations are generated by the staging compiler and bridge the generic
 * Chronicle-Hash holder infrastructure to the replicated Chronicle-Map and its
 * associated set view. They provide strongly typed access to the underlying
 * map while keeping the wiring details out of user code.
 * <p>
 * This interface is internal to Chronicle-Map and is not part of the public
 * API surface.
 */
@Staged
public interface ReplicatedChronicleMapHolder<K, V, R> extends VanillaChronicleMapHolder<K, V, R> {

    @Override
    ReplicatedChronicleMap<K, V, R> m();
}
