= Chronicle Map Replication (Enterprise Edition feature)
Neil Clifford
:toc: macro
:toclevels: 1
:css-signature: demo
:toc-placement: macro
:icons: font

toc::[]

== Enterprise Edition
Chronicle Map Replication is part of Chronicle Queue Enterprise; which is commercially supported. Extended features include:

- *Replication* to ensure real-time backup of all your map data.
- *Resilience* support for robust fail-over and disaster recovery environments.

In addition, you will be fully supported by our technical experts.

For more information see https://chronicle.software/queue-enterprise/[Chronicle Queue Enterprise].

== Replication

Chronicle Queue Enterprise supports replication of Chronicle Maps over TCP/IP.

== TCP Background
TCP/IP is a reliable protocol. This means that, unless you have a network failure or hardware outage, the data is guaranteed to arrive.

== How Chronicle Map Replication works
An underlying Chronicle Queue is used to persist changes to the Map, and this is replicated using Chronicle Queue Enterprise
replication to one or more other Chronicle Maps. One underlying queue can be shared by multiple Maps, if required.
Replication never block Map gets or puts.

Maps are configured either as a source or as a sink, with a source acting as the source of changes, and the sinks following.
Replication occurs from source to sink and a slow consumer, or a dead sink, will not impact replication to other sinks or
the source Map's performance.

If a node goes offline then once it rejoins the cluster it will handshake and start synchronising itself with the cluster.
The application can be notified when this process completes and the sink is up to date and replicating "live".

A new node can easily be created by connecting to the cluster, and then the new sink Map will become hydrated from the cluster.

The source can be changed. If, for example the master host or data centre is changed, and it typically takes only milliseconds to reconfigure the cluster with a new source, and restart replication.

'''
<<CM_Features.adoc#,Back to Features>>
